<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyTitle>Steam Achievement Unlocker</AssemblyTitle>
    <Product>Steam Achievement Unlocker</Product>
    <AssemblyName>Steam Achievement Unlocker</AssemblyName>
    <Description>Steam achievement management application.</Description>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Games\GameSelectionWindow.cs">
      <DependentUpon>GameSelectionWindow.xaml</DependentUpon>
    </Compile>
    <Compile Update="GameManager\GameManagerWindow.cs">
      <DependentUpon>GameManagerWindow.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SteamIntegration\SteamIntegration.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.2.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Fody" Version="6.9.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
